#!/usr/bin/env node
/**
 * process-images.mjs — Generate responsive WebP/AVIF variants
 * from local images. Updates src/data/content/gallery.ts with
 * width/height/alt + responsive srcset.
 *
 * Usage:
 *   node scripts/process-images.mjs                    # process all images
 *   node scripts/process-images.mjs --dir <folder>    # process one folder
 *   node scripts/process-images.mjs --out <file>       # write to a different gallery file
 */

import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';

const VARIANTS = [
  { width: 400,  suffix: 'sm' },
  { width: 800,  suffix: 'md' },
  { width: 1200, suffix: 'lg' },
  { width: 1600, suffix: 'xl' },
];

const SUPPORTED = new Set(['.jpg', '.jpeg', '.png', '.tiff']);

async function processImage(inputPath, baseOutDir) {
  const ext = path.extname(inputPath).toLowerCase();
  if (!SUPPORTED.has(ext)) return null;

  const baseName = path.basename(inputPath, ext);
  const dir = path.dirname(inputPath);
  const outDir = baseOutDir ?? dir;
  await fs.mkdir(outDir, { recursive: true });

  const original = await fs.readFile(inputPath);
  const meta = await sharp(original).metadata();
  const variants = [];
  let primaryPath = null;
  let primaryW = 0;
  let primaryH = 0;

  for (const v of VARIANTS) {
    if (meta.width && v.width > meta.width) continue;

    const webpOut = path.join(outDir, `${baseName}-${v.suffix}.webp`);
    const info = await sharp(original)
      .rotate()
      .resize({ width: v.width, withoutEnlargement: true })
      .webp({ quality: 75, effort: 6 })
      .toFile(webpOut);

    variants.push({ src: '/' + path.relative(process.cwd(), webpOut), w: info.width });
    if (info.width > primaryW) {
      primaryW = info.width;
      primaryH = info.height;
      primaryPath = '/' + path.relative(process.cwd(), webpOut);
    }
  }

  return {
    src: primaryPath,
    w: primaryW,
    h: primaryH,
    variants,
  };
}

async function walk(dir) {
  const out = [];
  async function recurse(d) {
    const entries = await fs.readdir(d, { withFileTypes: true });
    for (const e of entries) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) {
        if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
        await recurse(p);
      } else if (e.isFile() && SUPPORTED.has(path.extname(e.name).toLowerCase())) {
        out.push(p);
      }
    }
  }
  await recurse(dir);
  return out;
}

async function main() {
  const args = process.argv.slice(2);
  const dirIdx = args.indexOf('--dir');
  const targetDir = dirIdx >= 0 ? args[dirIdx + 1] : 'public/images/source';

  const exists = await fs.stat(targetDir).catch(() => null);
  if (!exists) {
    console.log(`Source directory "${targetDir}" does not exist.`);
    console.log('Drop JPEGs/PNGs there first, or pass --dir <path>.');
    return;
  }

  console.log(`Processing images in: ${targetDir}`);
  const files = await walk(targetDir);
  console.log(`Found ${files.length} source image(s).`);

  const entries = [];
  for (const f of files) {
    const result = await processImage(f);
    if (result) {
      entries.push({
        ...result,
        alt: path.basename(f, path.extname(f)).replace(/[-_]/g, ' '),
        placeholder: false,
      });
    }
  }

  const galleryOut = 'src/data/content/gallery.generated.ts';
  const body =
    '// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand\n' +
    'export const generatedGallery = ' +
    JSON.stringify(entries, null, 2) +
    ' as const;\n';

  await fs.mkdir(path.dirname(galleryOut), { recursive: true });
  await fs.writeFile(galleryOut, body);

  console.log(`Generated ${entries.length} image entry/entries.`);
  console.log(`Wrote: ${galleryOut}`);
  console.log('Import in your page as: import { generatedGallery } from \'./gallery.generated\'');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
